name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ssh run
        uses: appleboy/ssh-action@master
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${PASSWORD}
          script: |
            GITHUB_REPOSITORY=${{ github.repository }}
            cd ~/APP/ 
            dir=${GITHUB_REPOSITORY#*/}
            echo "repository: ${GITHUB_REPOSITORY}"
            echo "dir_name: $dir"
            if [ ! -d $dir ];then 
              git clone git@github.com:${GITHUB_REPOSITORY}.git
            fi
            cd $dir &&
            git pull && 
            export PASSWORD=${PASSWORD} &&
            bash ./install.sh
