name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ssh run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/APP/ 
            dir=$(echo "${GITHUB_REPOSITORY}" | cut -d "/" -f 2)
            echo ${GITHUB_REPOSITORY}
            echo $dir
            test -d $dir || git pull git@github.com:${GITHUB_REPOSITORY}.git
            cd $dir || bash ./install.sh
