name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ssh run
        uses: appleboy/ssh-action@master
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${PASSWORD}
          script: |
            GITHUB_REPOSITORY=${{ github.repository }}
            cd ~/APP/ 
            dir=${GITHUB_REPOSITORY#*/}
            echo "repository: ${GITHUB_REPOSITORY}"
            echo "dir_name: $dir"
            if [ ! -d $dir ];then 
              git clone git@github.com:${GITHUB_REPOSITORY}.git
            fi
            cd $dir && {
              git pull --rebase
              echo ${{ secrets.PASSWORD }} | sudo -S -v
              source ./install.sh
            }
      - name: send telegram message on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            <font color=green>*[Build SUCCESS]*</font> ${{ github.repository }}

            Commit message: ${{ github.event.commits[0].message }}

            [See Changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

      - name: send telegram message on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            <font color=red>*[Build FAILURE]*</font> ${{ github.repository }}

            [See Error Log](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
