name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/APP/ 
            dir=${GITHUB_REPOSITORY#*/}
            test -d $dir || git pull git@github.com:${GITHUB_REPOSITORY}.git
            cd $dir || bash ./install.sh
